get element js using dom
GSG-FC03/ToDoList-team6 pull request #20
Opened 2021-07-16 12:19 UTC by mo7amedehab97

bring  elements to the js file  using dom to working on them 
relates #18

2021-07-16 13:21 UTC, safamohanna95 submitted a review, later dismissed

2021-07-16 21:46 UTC, lina-jamal submitted a review, later dismissed

2021-07-17 13:37 UTC, Mosab-Ahmed requested changes
resolve conflict

2021-07-17 14:08 UTC, lina-jamal approved these changes

2021-07-17 14:10 UTC, Mosab-Ahmed approved these changes

2021-07-17 17:02 UTC, safamohanna95 approved these changes

2021-07-17 17:14 UTC, merged